### ISSUE TITLE
请问预热带来的性能提升有多少？

### ISSUE THREAD

**Issue by INotWant** [wangkaish/ali_race2020_r1_tail_base#1]
### 请问预热带来的性能提升有多少？

`谢谢～～`

**Comment by wangkaish** [comment]
> ### 请问预热带来的性能提升有多少？
> `谢谢～～`

大概300多ms，数字不准确（没有专门统计，加上抖动因素），因为本身代码比较容易较快触发jit，所以不会提升特别多

**Comment by INotWant** [comment]
> > ### 请问预热带来的性能提升有多少？
> > `谢谢～～`
> 
> 大概300多ms，数字不准确（没有专门统计，加上抖动因素），因为本身代码比较容易较快触发jit，所以不会提升特别多

明白了，谢谢！
